version: 2.1
jobs:
  build:
    docker:
      - image: python:3
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: 
          command: |
            python unit_test.py
            echo Hello World
            
      
